import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'vi' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  vi: {
    'home': 'Trang chủ',
    'courses': 'Khóa học',
    'my_courses': 'Khóa học của tôi',
    'about_us': 'Giới thiệu',
    'contact': 'Liên hệ',
    'profile': 'Hồ sơ',
    'logout': 'Đăng xuất',
    'digital_education_tagline': 'Nền tảng học tập trực tuyến hàng đầu Việt Nam, đem đến trải nghiệm học tập hiệu quả và tiện lợi.',
    'quick_links': 'Liên kết nhanh',
    'course_categories': 'Khóa học',
    'support': 'Hỗ trợ',
    'contact_info': 'Liên hệ',
    'email': 'Email',
    'hotline': 'Hotline',
    'address': 'Địa chỉ',
    'all_rights_reserved': 'Tất cả quyền được bảo lưu.',
    'explore_favorite_fields': 'Khám phá lĩnh vực yêu thích',
    'programming_it_courses': 'Khóa học lập trình & CNTT',
    'learn_programming_desc': 'Học lập trình với các ngôn ngữ hot nhất, phát triển web, ứng dụng di động, trí tuệ nhân tạo và nhiều lĩnh vực CNTT khác.',
    'explore_now': 'Khám phá ngay',
    'english_certificate_courses': 'Khóa học tiếng Anh & chứng chỉ',
    'ielts_toeic_desc': 'Luyện thi IELTS, TOEIC, tiếng Anh giao tiếp và các khóa học ngôn ngữ chất lượng cao với giáo viên giỏi.',
    'why_choose_digital_education': 'Tại sao chọn Digital Education?',
    'top_quality': 'Chất lượng hàng đầu',
    'experienced_teachers_desc': 'Đội ngũ giảng viên giàu kinh nghiệm, chương trình học được thiết kế chuyên sâu.',
    'reasonable_fees': 'Học phí hợp lý',
    'affordable_fees_desc': 'Mức học phí phù hợp với nhiều đối tượng học viên, cam kết chất lượng tương xứng.',
    'flexible_learning': 'Học linh hoạt',
    'flexible_learning_desc': 'Học mọi lúc, mọi nơi với nền tảng học trực tuyến thân thiện và dễ sử dụng.',
    'start_your_learning_journey': 'Sẵn sàng bắt đầu hành trình học tập của bạn?',
    'free_trial_desc': 'Đăng ký học thử miễn phí ngay hôm nay và trải nghiệm phương pháp học hiệu quả tại Digital Education.',
    'register_for_free_trial': 'Đăng ký học thử miễn phí',
    'my_classes': 'Lớp học của tôi',
    'view_all_classes': 'Xem tất cả lớp học',
    'collapse': 'Thu gọn',
    'no_registered_courses': 'Bạn chưa đăng kí khóa học nào',
    'explore_our_courses_desc': 'Khám phá các khóa học hấp dẫn của chúng tôi và đăng kí ngay hôm nay!',
    'course_materials': 'Tài liệu khóa học',
    'download': 'Tải xuống',
    'view': 'Xem',
    'cannot_view_file': 'Không thể xem trực tiếp loại tệp này. Vui lòng tải xuống.',
    'downloading': 'Đang tải xuống',
    'course_assignments': 'Bài tập của khóa học',
    'due_date': 'Hạn nộp',
    'expired': 'Đã hết hạn',
    'completed': 'Đã hoàn thành',
    'in_progress': 'Đang làm',
    'not_opened': 'Chưa mở',
    'score': 'Điểm',
    'teacher_comment': 'Nhận xét',
    'submitted_at': 'Nộp lúc',
    'view_details': 'Xem chi tiết',
    'submit_assignment': 'Nộp bài',
    'assignment_will_open': 'Bài tập sẽ được mở sau khi bạn hoàn thành Bài tập',
    'study_schedule': 'Lịch học',
    'status': 'Trạng thái',
    'next_session': 'Buổi học tới sẽ diễn ra vào ngày mai',
    'please_prepare': 'Vui lòng chuẩn bị bài tập và câu hỏi trước giờ học.',
    'this_week': 'Tuần này',
    'next_week': 'Tuần sau',
    'instructor': 'Giảng viên',
    'go_to_class': 'Vào học',
    'assignment_details': 'Chi tiết bài tập',
    'assignment_submission': 'Nộp bài tập',
    'select_files_to_submit': 'Chọn tệp để nộp (có thể chọn nhiều tệp)',
    'select_files': 'Chọn tệp',
    'cancel': 'Hủy',
    'submit': 'Nộp bài',
    'hello': 'Xin chào',
    'welcome_back': 'Chào mừng bạn quay trở lại với khóa học',
    'your_study_progress': 'Tiến độ học tập của bạn',
    'completed_progress': 'Hoàn thành',
    'explore_more_courses': 'Khám phá thêm khóa học',
    'sign_in': 'Đăng nhập',
    'register_now': 'Đăng ký ngay',
    'register_trial_course': 'Đăng ký học thử',
    'basic_python_programming': 'Lập trình Python cơ bản',
    'ielts_in_3_months': 'IELTS 6.0+ trong 3 tháng',
    'web_design_html_css_javascript': 'Thiết kế web với HTML, CSS và JavaScript',
    'advanced_math_grade_12': 'Toán cao cấp cho lớp 12',
    'toeic_in_2_months': 'TOEIC 750+ trong 2 tháng',
    'mobile_app_development_react_native': 'Lập trình ứng dụng di động với React Native',
    'university_physics_prep': 'Luyện thi đại học môn Vật lý',
    'conversational_english': 'Luyện nói tiếng Anh giao tiếp',
    'days': 'ngày',
    'hours': 'giờ',
    'minutes': 'phút',
    'at': 'lúc',
    'about_us_digital_education': 'Về Chúng Tôi - Digital Education',
    'world_changing_part1': 'Trong một thế giới đang chuyển mình mạnh mẽ bởi công nghệ,',
    'education_is_a_right': 'giáo dục không còn là đặc quyền, mà là quyền lợi của tất cả mọi người',
    'vision_statement_part1': 'Chúng tôi tin rằng',
    'vision_statement_quote': '"mỗi cá nhân đều có tiềm năng vươn xa nếu được tiếp cận đúng tri thức, đúng phương pháp và đúng thời điểm"',
    'vision_statement_part2': 'Digital Education không chỉ đơn thuần là một nền tảng học trực tuyến, mà là một hệ sinh thái giáo dục toàn diện – nơi mọi người có thể học hỏi, kết nối và phát triển bền vững.',
    'our_mission': 'Sứ Mệnh Của Chúng Tôi',
    'mission_statement_part1': 'Sứ mệnh của chúng tôi là',
    'mission_statement_quote': '"Mang lại cơ hội học tập chất lượng cao cho mọi người, không phân biệt độ tuổi, nghề nghiệp hay nơi sinh sống"',
    'mission_statement_part2': 'Dù bạn là học sinh, sinh viên, người đi làm hay người đang tìm hướng đi mới, Digital Education đều có thể trở thành người bạn đồng hành đáng tin cậy trong hành trình học tập của bạn.',
    'what_makes_us_special': 'Chúng Tôi Có Gì Đặc Biệt?',
    'feature_courses_title': '500+ Khóa Học Chất Lượng',
    'feature_courses_desc': 'Được thiết kế bởi các chuyên gia đầu ngành, từ cơ bản đến nâng cao',
    'feature_content_title': 'Nội Dung Cập Nhật',
    'feature_content_desc': 'Bám sát xu hướng thực tiễn và nhu cầu thị trường',
    'feature_community_title': 'Cộng Đồng Học Tập',
    'feature_community_desc': 'Diễn đàn trao đổi, hỏi đáp và chia sẻ kinh nghiệm',
    'development_journey_title': 'Hành Trình Phát Triển',
    'development_journey_desc_part1': 'Bắt đầu từ một nhóm những người yêu giáo dục và công nghệ, chúng tôi đã không ngừng nỗ lực để xây dựng một nền tảng học tập uy tín.',
    'development_journey_desc_highlight': '10.000 học viên',
    'development_journey_desc_part2': 'trên toàn quốc và đang mở rộng ra thị trường quốc tế.',
    'join_our_community_title': 'Hãy Gia Nhập Cộng Đồng Học Tập Của Chúng Tôi!',
    'join_our_community_desc': 'Nếu bạn đang tìm kiếm một nơi để nâng cao kiến thức, phát triển kỹ năng và chạm đến những ước mơ nghề nghiệp – thì bạn đã tìm đúng địa chỉ.',
    'digital_education_slogan': 'Digital Education – Học tập không giới hạn, phát triển không ngừng.',
    'explore_courses': 'Khám phá các khóa học',
    'explore_courses_desc': 'Tìm kiếm và đăng ký các khóa học phù hợp với nhu cầu và mục tiêu học tập của bạn.',
    'search_courses': 'Tìm kiếm khóa học',
    'search_courses_placeholder': 'Nhập tên khóa học, giáo viên...',
    'field': 'Lĩnh vực',
    'level': 'Cấp độ',
    'results': 'Kết quả',
    'no_courses_found': 'Không tìm thấy khóa học nào',
    'try_different_search_criteria': 'Vui lòng thử lại với các tiêu chí tìm kiếm khác.',
    'all': 'Tất cả',
    'admin_dashboard_title': 'Bảng Điều Khiển Quản Trị',
    'manage_courses': 'Quản lý khóa học',
    'manage_users': 'Quản lý người dùng',
    'manage_assignments': 'Quản lý bài tập',
    'manage_roles': 'Phân quyền',
    'view_statistics': 'Thống kê',
    'mailbox': 'Hộp thư',
    'settings': 'Cài đặt',
    'course_management': 'Quản lý Khóa học',
    'add_new_course': 'Thêm khóa học mới',
    'course_id': 'Mã khóa học',
    'course_title': 'Tên khóa học',
    'category': 'Danh mục',
    'teacher': 'Giảng viên',
    'actions': 'Hành động',
    'user_management': 'Quản lý Người dùng',
    'add_new_user': 'Thêm người dùng mới',
    'user_id': 'Mã người dùng',
    'user_name': 'Tên người dùng',
    'user_email': 'Email người dùng',
    'user_role': 'Vai trò',
    'user_status': 'Trạng thái',
    'assignment_management': 'Quản lý Bài tập',
    'add_new_assignment': 'Thêm bài tập mới',
    'assignment_id': 'Mã bài tập',
    'assignment_title': 'Tên bài tập',
    'assignment_course': 'Khóa học',
    'assignment_due_date': 'Ngày hết hạn',
    'assignment_status': 'Trạng thái',
    'role_management': 'Quản lý Phân quyền',
    'add_new_role': 'Thêm vai trò mới',
    'role_id': 'Mã vai trò',
    'role_name': 'Tên vai trò',
    'role_description': 'Mô tả',
    'role_description_table_header': 'Mô tả vai trò',
    'fill_role_details': 'Điền thông tin vai trò mới vào đây. Nhấn thêm khi hoàn tất.',
    'confirm_delete_role': 'Bạn có chắc chắn muốn xóa vai trò này không? Hành động này không thể hoàn tác.',
    'edit_role': 'Chỉnh sửa vai trò',
    'edit_role_details': 'Chỉnh sửa thông tin vai trò tại đây. Nhấn cập nhật khi hoàn tất.',
    'update_role': 'Cập nhật vai trò',
    'statistics_view': 'Xem Thống kê',
    'statistics_view_desc': 'Số lượng người dùng, khóa học và bài nộp gần đây',
    'mailbox_desc': 'Xem và quản lý các phản hồi từ người dùng',
    'settings_desc': 'Cấu hình hệ thống, thông báo',
    'role_description_admin': 'Toàn quyền truy cập vào tất cả các tính năng và cài đặt hệ thống.',
    'role_description_teacher': 'Có thể quản lý khóa học, bài tập và xem tiến độ học tập của học sinh.',
    'role_description_student': 'Có thể đăng ký khóa học, truy cập tài liệu học tập và nộp bài tập.',
    'time_left': 'Thời gian còn lại',
  },
  en: {
    'home': 'Home',
    'courses': 'Courses',
    'my_courses': 'My Courses',
    'about_us': 'About Us',
    'contact': 'Contact',
    'profile': 'Profile',
    'logout': 'Logout',
    'digital_education_tagline': 'Vietnam\'s leading online learning platform, offering an effective and convenient learning experience.',
    'quick_links': 'Quick Links',
    'course_categories': 'Courses',
    'support': 'Support',
    'contact_info': 'Contact Info',
    'email': 'Email',
    'hotline': 'Hotline',
    'address': 'Address',
    'all_rights_reserved': 'All rights reserved.',
    'explore_favorite_fields': 'Explore Favorite Fields',
    'programming_it_courses': 'Programming & IT Courses',
    'learn_programming_desc': 'Learn programming with the hottest languages, web development, mobile applications, artificial intelligence, and many other IT fields.',
    'explore_now': 'Explore Now',
    'english_certificate_courses': 'English & Certificate Courses',
    'ielts_toeic_desc': 'IELTS, TOEIC, conversational English, and high-quality language courses with excellent teachers.',
    'why_choose_digital_education': 'Why Choose Digital Education?',
    'top_quality': 'Top Quality',
    'experienced_teachers_desc': 'Experienced teaching staff, in-depth curriculum design.',
    'reasonable_fees': 'Reasonable Fees',
    'affordable_fees_desc': 'Affordable tuition fees for various student groups, committed to equivalent quality.',
    'flexible_learning': 'Flexible Learning',
    'flexible_learning_desc': 'Learn anytime, anywhere with a user-friendly and convenient online learning platform.',
    'start_your_learning_journey': 'Ready to start your learning journey?',
    'free_trial_desc': 'Register for a free trial today and experience effective learning methods at Digital Education.',
    'register_for_free_trial': 'Register for Free Trial',
    'my_classes': 'My Classes',
    'view_all_classes': 'View all classes',
    'collapse': 'Collapse',
    'no_registered_courses': 'You have not registered for any courses yet',
    'explore_our_courses_desc': 'Explore our exciting courses and register today!',
    'course_materials': 'Course Materials',
    'download': 'Download',
    'view': 'View',
    'cannot_view_file': 'Cannot view this file type directly. Please download.',
    'downloading': 'Downloading',
    'course_assignments': 'Course Assignments',
    'due_date': 'Due Date',
    'expired': 'Expired',
    'completed': 'Completed',
    'in_progress': 'In progress',
    'not_opened': 'Not opened yet',
    'score': 'Score',
    'teacher_comment': 'Teacher Comment',
    'submitted_at': 'Submitted at',
    'view_details': 'View Details',
    'submit_assignment': 'Submit Assignment',
    'assignment_will_open': 'Assignment will open after you complete Assignment',
    'study_schedule': 'Study Schedule',
    'status': 'Status',
    'next_session': 'The next session will take place tomorrow',
    'please_prepare': 'Please prepare assignments and questions before class.',
    'this_week': 'This Week',
    'next_week': 'Next Week',
    'instructor': 'Instructor',
    'go_to_class': 'Go to Class',
    'assignment_details': 'Assignment Details',
    'assignment_submission': 'Assignment Submission',
    'select_files_to_submit': 'Select files to submit (can select multiple files)',
    'select_files': 'Select files',
    'cancel': 'Cancel',
    'submit': 'Submit',
    'hello': 'Hello',
    'welcome_back': 'Welcome back to the course',
    'your_study_progress': 'Your Study Progress',
    'completed_progress': 'Completed',
    'explore_more_courses': 'Explore more courses',
    'sign_in': 'Sign In',
    'register_now': 'Register Now',
    'register_trial_course': 'Register for Trial Course',
    'basic_python_programming': 'Basic Python Programming',
    'ielts_in_3_months': 'IELTS 6.0+ in 3 months',
    'web_design_html_css_javascript': 'Web Design with HTML, CSS, and JavaScript',
    'advanced_math_grade_12': 'Advanced Math for Grade 12',
    'toeic_in_2_months': 'TOEIC 750+ in 2 months',
    'mobile_app_development_react_native': 'Mobile App Development with React Native',
    'university_physics_prep': 'University Physics Prep',
    'conversational_english': 'Conversational English Practice',
    'days': 'days',
    'hours': 'hours',
    'minutes': 'minutes',
    'at': 'at',
    'about_us_digital_education': 'About Us - Digital Education',
    'world_changing_part1': 'In a world rapidly transforming by technology,',
    'education_is_a_right': 'education is no longer a privilege, but a right for everyone',
    'vision_statement_part1': 'We believe that',
    'vision_statement_quote': '\'every individual has the potential to go further if they have access to the right knowledge, the right method, and at the right time\'',
    'vision_statement_part2': 'Digital Education is not just an online learning platform, but a comprehensive educational ecosystem – where everyone can learn, connect, and develop sustainably.',
    'our_mission': 'Our Mission',
    'mission_statement_part1': 'Our mission is to',
    'mission_statement_quote': '\'Provide high-quality learning opportunities for everyone, regardless of age, profession, or location\'',
    'mission_statement_part2': 'Whether you are a student, a working professional, or someone looking for a new direction, Digital Education can be your reliable companion on your learning journey.',
    'what_makes_us_special': 'What Makes Us Special?',
    'feature_courses_title': '500+ Quality Courses',
    'feature_courses_desc': 'Designed by leading industry experts, from basic to advanced',
    'feature_content_title': 'Updated Content',
    'feature_content_desc': 'Closely follows practical trends and market demands',
    'feature_community_title': 'Learning Community',
    'feature_community_desc': 'Forum for discussion, Q&A, and sharing experiences',
    'development_journey_title': 'Development Journey',
    'development_journey_desc_part1': 'Starting as a group of people passionate about education and technology, we have continuously strived to build a reputable learning platform.',
    'development_journey_desc_highlight': '10,000 students',
    'development_journey_desc_part2': 'nationwide and expanding into the international market.',
    'join_our_community_title': 'Join Our Learning Community!',
    'join_our_community_desc': 'If you are looking for a place to enhance your knowledge, develop skills, and achieve your career dreams – you have come to the right place.',
    'digital_education_slogan': 'Digital Education – Learning without limits, continuous development.',
    'explore_courses': 'Explore Courses',
    'explore_courses_desc': 'Search and register for courses that fit your needs and learning goals.',
    'search_courses': 'Search Courses',
    'search_courses_placeholder': 'Enter course name, teacher...',
    'field': 'Field',
    'level': 'Level',
    'results': 'Results',
    'no_courses_found': 'No courses found',
    'try_different_search_criteria': 'Please try again with different search criteria.',
    'all': 'All',
    'admin_dashboard_title': 'Admin Dashboard',
    'manage_courses': 'Manage Courses',
    'manage_users': 'Manage Users',
    'manage_assignments': 'Manage Assignments',
    'manage_roles': 'Manage Roles',
    'view_statistics': 'View Statistics',
    'mailbox': 'Mailbox',
    'settings': 'Settings',
    'course_management': 'Course Management',
    'add_new_course': 'Add New Course',
    'course_id': 'Course ID',
    'course_title': 'Course Title',
    'category': 'Category',
    'teacher': 'Teacher',
    'actions': 'Actions',
    'user_management': 'User Management',
    'add_new_user': 'Add New User',
    'user_id': 'User ID',
    'user_name': 'User Name',
    'user_email': 'User Email',
    'user_role': 'User Role',
    'user_status': 'User Status',
    'assignment_management': 'Assignment Management',
    'add_new_assignment': 'Add New Assignment',
    'assignment_id': 'Assignment ID',
    'assignment_title': 'Assignment Title',
    'assignment_course': 'Course',
    'assignment_due_date': 'Due Date',
    'assignment_status': 'Status',
    'role_management': 'Role Management',
    'add_new_role': 'Add New Role',
    'role_id': 'Role ID',
    'role_name': 'Role Name',
    'role_description': 'Description',
    'role_description_table_header': 'Role Description',
    'fill_role_details': 'Fill in the new role details here. Press add when done.',
    'confirm_delete_role': 'Are you sure you want to delete this role? This action cannot be undone.',
    'edit_role': 'Edit Role',
    'edit_role_details': 'Edit the role details here. Press update when done.',
    'update_role': 'Update Role',
    'statistics_view': 'View Statistics',
    'statistics_view_desc': 'Number of users, courses, and recent submissions',
    'mailbox_desc': 'View and manage user feedback',
    'settings_desc': 'System configuration, notifications',
    'role_description_admin': 'Full access to all system features and settings.',
    'role_description_teacher': 'Can manage courses, assignments, and view student progress.',
    'role_description_student': 'Can enroll in courses, access learning materials, and submit assignments.',
    'time_left': 'Time Left',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('vi'); // Default to Vietnamese

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 